### ISSUE TITLE
Mixins Conflict

### ISSUE THREAD

**Issue by monkee-ch** [DjangoAdminHackers/django-admin-row-actions#10]
Is it correct, that AdminRowActionsMixin and DjangoObjectActions are not compatible?
They work perfectly on their own, but combined, i cannot get them both to work.

If i disable:
`# objectactions = ('print_odt',)`
AdminRowActionsMixins work, and vice versa.

`class InvoiceAdmin(DjangoObjectActions, AdminRowActionsMixin, admin.ModelAdmin)`

Error Message:
`Page not found (404)
Request Method: 	GET
Request URL: 	http://localhost:8000/admin/sales/invoice/279/rowactions/set_payment/
Raised by: 	django.contrib.admin.options.change_view`

A hint how to solve this?

**Comment by andybak** [comment]
I'm using them both together. Half the point was the ability to reuse object actions as row actions where appropriate.

Could you show a bit more of your code? Can you also try switching to the get_row_actions method instead of the rowactions property? I tend the use the method so it could be a bug in the handling of the property.

**Comment by monkee-ch** [comment]
```
    def print_relatorio_odt(self, request, obj):
        return self.print_relatorio_invoice(request, obj, "ODT")
    print_relatorio_odt.label = "Rechnung drucken"  # optional
    print_relatorio_odt.short_description = "Ein ODT Dokument der Rechnung erstellen"
    print_relatorio_odt.attrs = {
        'class': 'printLink fa fa-print',
    }
```
    
```
def get_row_actions(self, obj):
        row_actions = [
            {
                'label': 'Einzahlung buchen',
                'tooltip': 'Einzahlung verbuchen',
                'action': 'set_payment'
            },
            {
                'label': 'Bezahlte Rechnung',
                'tooltip': 'Rechnung auf bezahlt setzen',
                'action': 'set_paid'
            },
            {
                'label': 'Offene Rechnung',
                'tooltip': 'Rechnung auf bezahlt setzen',
                'action': 'set_open'
            },
        ]
        row_actions += super(InvoiceAdmin, self).get_row_actions(obj)
        return row_actions

    #actions = [invoice_open,invoice_sent,invoice_paid]
    objectactions = ('print_relatorio_odt',)
```


If i comment out "objectactions", row_actions work, if i comment out the row_actions, the objectactions (detail view) work.

Thanks a lot for your feedback, as i am really stuck on this one.

**Comment by monkee-ch** [comment]
class InvoiceAdmin(DjangoObjectActions, AdminRowActionsMixin, admin.ModelAdmin)
-->  ObjectActions work! RowActionsMixin fails

class InvoiceAdmin( AdminRowActionsMixin, DjangoObjectActions, admin.ModelAdmin)
-->  RowActionsMixin work!  ObjectActions fails


So for me it seems like these two are not compatible.

**Comment by andybak** [comment]
When I have a free moment I'll try out an existing project to see if I can recreate the problem.

**Comment by monkee-ch** [comment]
Found the Bug!

I was using django_object_actions 0.7.0   (do not know why)

Now in combination with with django_object_actions 0.9.0 everything works!

Thanks for your Time!

**Comment by andybak** [comment]
Glad you solved it. Sorry I wasn't more help.
